# Generated by Django 4.1.7 on 2023-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.CharField(
                choices=[
                    ("DG", "Dog"),
                    ("CT", "Cat"),
                    ("RB", "Rabbit"),
                    ("AC", "Accessories"),
                ],
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
