# Generated by Django 4.1.7 on 2023-05-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_products_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.CharField(
                choices=[
                    ("DOGS", "Dog"),
                    ("CATS", "Cat"),
                    ("RABBITS", "Rabbit"),
                    ("ACCESSORIES", "Accessories"),
                ],
                max_length=50,
            ),
        ),
    ]
