# Generated by Django 4.1.7 on 2023-05-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_products_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.CharField(
                choices=[
                    ("Dogs", "Dog"),
                    ("Cats", "Cat"),
                    ("Rabbits", "Rabbit"),
                    ("Accessories", "Accessories"),
                ],
                max_length=50,
            ),
        ),
    ]
